### ISSUE TITLE
Allow alternative entropy inputs

### ISSUE THREAD

**Issue by taxmeifyoucan** [PatriceVignola/cpp-kzg-ceremony-client#34]
The option `--entropy` is required and allows only text input in the argument. That means that by default, the command with potentially toxic entropy data is stored in shell history. 

Proposed solution: 
Use stdin as default entropy input. `--entropy` flag is no longer required and if it is not provided, the program prompts user to enter the entropy. 
Other nice to have feature would be to supply the entropy via pipe in shell. Or also pull it from a remote server -  https call without revealing the toxic data is a secure option and it could used with https://proofof.cat entropy source.

**Comment by PatriceVignola** [comment]
Thanks for the input!

Good point on the entropy issue, even though there's a second layer of randomness based on the machine's CSPRNG, it would be safer to have it not leak outside of the program.

I also plan to add more sources of entropy soon; getting it from an https call is a good idea.

**Comment by PatriceVignola** [comment]
Interactive `cin` entropy is now supported.
