### ISSUE TITLE
Ethereum address `0x......` doesn't start with `0x`

### ISSUE THREAD

**Issue by notastudio** [PatriceVignola/cpp-kzg-ceremony-client#41]
I ran this client with the Ethereum authentication provider. After login with SIWE, it shows: Ethereum address `0x......` doesn't start with `0x`.

```
# ./cpp-kzg-ceremony-client
Generating secrets
Write a sentence to generate entropy: 
......
Retrieving the transcript
Validating transcript file against the schema
Validating the transcript's running products
Generating the pot pubkeys
Server is listening on port 16877
The authentication window should now open in your browser. If you close it by mistake or an error occurred during the authentication, you can manually access the following URL: 

https://oidc.signinwithethereum.org/......

Retrieving your identity
Ethereum address `0x......` doesn't start with `0x`

```
The client is on my server. I copy the SIWE URL to my browser and sign with MetaMask, and manually modify `localhost` in the callback URL to my server IP address. The web page shows I successfully authenticated.

**Comment by PatriceVignola** [comment]
@notastudio Thank you for the report! The ethereum auth path got broken in a recent refactoring change. You can use the older [v1.1.0 build](https://github.com/PatriceVignola/cpp-kzg-ceremony-client/releases/tag/v1.1.0) or the new [v.1.2.1 build](https://github.com/PatriceVignola/cpp-kzg-ceremony-client/releases/tag/v1.2.1) that just got fixed. Let me know how it goes!
