### ISSUE TITLE
Allow specifying local listening port

### ISSUE THREAD

**Issue by ulope** [PatriceVignola/cpp-kzg-ceremony-client#44]
Currently a random local port seems to be chosen.

This makes it difficult to run the client in a container since the port number has to be known before the container is started.

Please add a command line option to specify a port number.

**Comment by PatriceVignola** [comment]
You can now specify a port with the `--port` option in the [v1.3.0 release](https://github.com/PatriceVignola/cpp-kzg-ceremony-client/releases/tag/v1.3.0).
