### ISSUE TITLE
Error while trying to contribute. Rate limited?

### ISSUE THREAD

**Issue by notastudio** [PatriceVignola/cpp-kzg-ceremony-client#47]
While waiting for contributing, the client keeps showing:
```
Error while trying to contribute via https://seq.ceremony.ethereum.org/lobby/try_contribute: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: VmXtIuIAW_uiTTisR259cIi-8ihz_-75NTOt2XY_Qnj1mi0DADdSKQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>. We will keep trying to contribute.
```
Looks like the client is rate limited.

**Comment by PatriceVignola** [comment]
The expected rate limited response for this endpoint is error 400. 403 is an unexpected response and could be caused by many reasons, including the server receiving too many connections.

When you got this error for the first time, approximately for how long had you been trying to contribute? And are you still getting this error on every request?

**Comment by notastudio** [comment]
> When you got this error for the first time, approximately for how long had you been trying to contribute?

Maybe no more than 10 minutes?

> And are you still getting this error on every request?

Yes, every request. I killed the client and restarted it, now it gives the error when "Retrieving the transcript".

I tried both on my server and my PC (they are in different countries), and the error is the same. So maybe it's not about location or IP address.

**Comment by notastudio** [comment]
2 minutes after starting the client, it gives
```
Error while trying to contribute via https://seq.ceremony.ethereum.org/lobby/try_contribute: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
. We will keep trying to contribute.
```
this type of error is not shown on every request.
And 5 minutes after, it gives the aforementioned CloudFront error on every request.

**Comment by PatriceVignola** [comment]
Error 503 especially suggests that there may be something wrong with the server, but it's hard to be sure. Some clients also use the same pinging frequency as this one (once every second), so I don't think it's pinging too often. I used this client to contribute when there were 3000 people in the lobby and I didn't have any issues, but maybe the rate limiting rules changed in-between or the server conditions may be different.

Either way, I'll be able to investigate more and report back in a few hours when I have access to my PC.

**Comment by PatriceVignola** [comment]
@notastudio I increased the retry delay to a conservative amount and it seems to work fine now. You can try it out in [version 1.3.1](https://github.com/PatriceVignola/cpp-kzg-ceremony-client/releases/tag/v1.3.1).

**Comment by notastudio** [comment]
It works, thanks!
